[versions]
minestom = "2026.02.09-1.21.11"
arrow = "2.2.1.1"
slf4j = "2.0.16"
log4j = "2.25.3"
kotlin-logging = "7.0.3"

[libraries]
minestom = { group = "net.minestom", name = "minestom", version.ref = "minestom" }
arrow-core = { group = "io.arrow-kt", name = "arrow-core", version.ref = "arrow" }
arrow-fx-coroutines = { group = "io.arrow-kt", name = "arrow-fx-coroutines", version.ref = "arrow" }

# Logging
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
log4j-slf4j-impl = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4j" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "kotlin-logging" }